### PR TITLE
Needinfo regression author when "regressed by" field is set on new bugs

### LINKED ISSUE #1247: Needinfo regression author when "regressed by" field is set on new bugs
As discussed, we should needinfo the person assigned to the regressing bug if a bug isn't assigned already to someone.

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #1247

Still left to do: don't needinfo if the regressor author already interacted with the bug (by commenting or doing some other action in the bug).

### CODE REVIEW

**Comment by marco-c** [comment]
@calixteman can you take a look and tell me if you see some other case where we should avoid needinfoing?

**Comment by calixteman** [comment]
What you said is correct and maybe the same for the manager of the author and the triage owner if no manager.

**Comment by marco-c** [comment]
I've added the skipping of bugs the regressor author already interacted with.
Here's the list of bugs from a dry run:



Bug | Summary
-- | --
1754850 | Intermittent TV image/test/mochitest/test_image_cache_notification.html \| second load of over.png should be cached
1754592 | With HCM enabled and Firefox's default theme, primary buttons' focus rings are invisible
1754455 | Intermittent TVw-fis TinderboxPrint: Per-test run of .../opaque-origin.html<br/>: FAILURE
1754138 | Intermittent [TVw] Return code: 1 after focus-method-delegatesFocus-nested-browsing-context.html
1754074 | [vaapi] Video decode attempts to use incorrect EGL display
1753849 | Intermittent browser/components/places/tests/browser/browser_controller_onDrop_query.js \| Test timed out -
1753829 | Intermittent [TVw] TinderboxPrint: Per-test run of .../first-letter-punctuation-317.xht<br/>: FAILURE
1753828 | Intermittent [TVw] TinderboxPrint: Per-test run of .../margin-applies-to-006.xht<br/>: FAILURE
1753607 | Creating a tab with the openerTabId of the discarded tab resulted in an unexpected error
1753525 | Hand-off Dock icon bounces in and out frequently during browsing on other macOS machine
1753477 | Intermittent TV  browser/base/content/test/siteIdentity/browser_bug906190.js \| Uncaught  exception received from previously timed out test - ViewShown listener  on #identity-popup not removed before the end of test
1753472 | Intermittent [TVw] ::: Test verification FAIL \|  TinderboxPrint: Per-test run of  .../streams/queuing-strategies.any.js<br/>: FAILURE
1753458 | Intermittent [TV] browser/components/preferences/tests/browser_moreFromMozilla.js \| Test timed out -

**Comment by calixteman** [comment]
Interesting to see so many "Intermittent...".
Could it mean that people pay less attention to those kind of issues ?

**Review by calixteman — APPROVED** [review]
What about checking if author's manager changed something in the bug ?
Anyway, r+=me.

**Comment by marco-c** [comment]
> What about checking if author's manager changed something in the bug ?

Let's first see if we get complaints, it should be a rare enough occurrence anyway

**Pull request merged**
