### PR TITLE
auto-approve bugs for expiring telemetry probes as tracking

### PR DESCRIPTION
**Pull request by Archaeopteryx**

### CODE REVIEW

**Comment by calixteman** [comment]
Thanks a lot for contributing.

Did you try to run in dry-run mode ?
`python -m auto_nag.scripts.telemetry_expiry_tracking_autoapproval -d`
to test that everything is ok it'd be better to test when a there will be a bug satisfying the search query.

Sometimes the bugzilla api is a bit weird and counterintuitive, did you try to update a tracking flag (I never did it myself so I don't know if what you wrote is correct) on https://bugzilla-dev.allizom.org/home ?
You can test if it works correctly in using this script:
```python
from libmozdata.bugzilla import Bugzilla

Bugzilla.URL = 'https://bugzilla-dev.allizom.org'
Bugzilla.API_URL = Bugzilla.URL + '/rest/bug'
Bugzilla.TOKEN = 'An Allizom TOKEN'

bug_id = '1631059'

data = {'blocks': {'add': ['1631058']}}
Bugzilla(bugids=[bug_id]).put(data)
``` 

And finally you need to update:
https://github.com/mozilla/relman-auto-nag/blob/master/runauto_nag_daily.sh
(or the hourly version if it makes sense to run that stuff hourly)

**Comment by Archaeopteryx** [comment]
A missing bugzilla group (``edittrackingflags`) has been identified which the bot has to be added to first ([1741910](https://bugzilla.mozilla.org/show_bug.cgi?id=1741910)). For testing with allizom, the Firefox version will be hardcoded (because of allizom's old data). The next such bug is supposed to be available on Dec 13, hence testing will happen on allizom. (Had tested the query for finding bugs with `+` instead of `?` for the approval state.)

**Comment by Archaeopteryx** [comment]
`data = {'cf_tracking_firefox77': '---'}` succeeded for [Bug 1619580](https://bugzilla-dev.allizom.org/show_bug.cgi?id=1619580#a54018754_258347).

**Comment by calixteman** [comment]
> `data = {'cf_tracking_firefox77': '---'}` succeeded for [Bug 1619580](https://bugzilla-dev.allizom.org/show_bug.cgi?id=1619580#a54018754_258347).
I had the feeling it was wrong... anyway it's always a good idea on allizom (when possible) to check if everything is ok.

**Comment by calixteman** [comment]
I'm fine with the patch.
As an advice, I think you should add a file `template/telemetry_expiry_tracking_autoapproval.html` similar to:
https://github.com/mozilla/relman-auto-nag/blob/master/templates/stalled.html
and add an entry similar to:
https://github.com/mozilla/relman-auto-nag/blob/171aa043848189d9d6a391390d8880e42924bb0a/auto_nag/scripts/configs/tools.json#L93-L100
and just put yourself as a receiver, this way you'll get emails when something has been changed by the bot.
It's mainly helpful at the beginning to see if everything is ok, or to see sometimes some devs complaining in a comment about the bot: so it could help to improve.
Anyway if you think that you don't need any feedback, I'm fine with that and just tell me.

**Comment by Archaeopteryx** [comment]
This should not be necessary because I will be the only person who will create such requests and hence notice if they don't get approved. I will talk to RelMan if they want to set up an alert in the future in case this is gonna break.

**Review by calixteman — APPROVED** [review]
LGTM

**Comment by calixteman** [comment]
I just updated the bot.
It doesn't run during the week-end, so next run is monday.
If you see something wrong, please ping me or Marco.

**Pull request merged**
