### PR TITLE
consistency: central_version => nightly version

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by jcristau** [comment]
Why, OOI?  This doesn't look particularly consistent to me...

**Comment by sylvestre** [comment]
@calixteman asked for this change in
https://github.com/mozilla/relman-auto-nag/pull/168 
https://github.com/mozilla/relman-auto-nag/pull/168/commits/0476700a28e7e4c9be1c796a464fab117faccc86
So, just to be consistent with this change

**Comment by sylvestre** [comment]
to be clear, I don't care :)

**Comment by calixteman** [comment]
@jcristau accept or reject it, it's up to you.
Here the consistency is to have the channel names.

**Comment by jcristau** [comment]
Well this leaves central in most places with nightly in a couple, I'd rather keep saying central everywhere.

**Pull request closed without merging**
