### PR TITLE
has_reg_range: fix it !

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by marco-c** [comment]
The script is redundant with the `regression` one, after we enable autofix for that one, we could remove this script.

**Comment by calixteman** [comment]
@marco-c are we sure that the confidence will always be enough in such a case ?

**Comment by marco-c** [comment]
Yes, there is an override rule in the model which makes the confidence 100% when there is `has_regression_range`.

**Comment by calixteman** [comment]
you cheated ;)

**Pull request merged**
