### PR TITLE
#983 - Identify intermittent bugs with 'intermittent-failure' keyword and not with id of bug reporter

### PR DESCRIPTION
**Pull request by Archaeopteryx**
Untested, similar to add recipes using `keywords` and based on the bugzilla queries.

### CODE REVIEW

**Comment by emceeaich** [comment]
The test `auto_nag.tests.test_regression_set_status_flags.TestSetStatusFlags` is failing with:

```
   KeyError: 'cf_status_firefox_esr2'
```
Looks like something in the mocks?

**Comment by emceeaich** [comment]
@calixteman I'm waiting to merge because of the failing test, but I don't think it's related to the PR. Should I go ahead and merge this?

**Comment by jcristau** [comment]
The fix for the test issue is on master, so I rebased this branch to grab it.  Now we're seeing flake8 errors though in auto_nag/scripts/close_intermittents.py.

**Comment by emceeaich** [comment]
@jcristau fixing that and will test local.

**Pull request merged**
