### PR TITLE
Use `.txt` extension for attached log files in emails

### PR DESCRIPTION
**Pull request by suhaibmujahid**
This will make it possible to preview the log files in Gmail without downloading them. Also, the content of the file will be searchable.

### CODE REVIEW

**Comment by marco-c** [comment]
What if instead we directly emit the log in a .txt file?

**Comment by suhaibmujahid** [comment]
> What if instead we directly emit the log in a .txt file?

It will work. Currently, the PR will only modify the file name in the email attachment; will not touch the actual file.

@marco-c do you suggest renaming the log file itself instead?

**Comment by marco-c** [comment]
Yep, that's what I was suggesting. Is there any drawback?

**Comment by suhaibmujahid** [comment]
> Yep, that's what I was suggesting. Is there any drawback?

Mainly the `.log` extension is more descriptive. 

Renaming the log file is as simple as modifying the following line:

https://github.com/mozilla/relman-auto-nag/blob/3940a99dd471b2da0e312249df547fac3f810a00/auto_nag/scripts/configs/tools.json#L66

I'm OK with both solutions.

**Comment by marco-c** [comment]
All right, let's just rename the extension in the config then

**Review by marco-c — APPROVED** [review]

**Pull request merged**
