### PR TITLE
Remove limitations from the hs_regression_range_no_keyword script

### PR DESCRIPTION
**Pull request by marco-c**
This would autofix ~600 bugs. Should we do it?

### CODE REVIEW

**Comment by sylvestre** [comment]
Maybe you can limit in time the change

**Comment by marco-c** [comment]
One month at a time?

**Comment by calixteman** [comment]
I think we should do that slowly to avoid to overwhelm the mail boxes.

**Comment by sylvestre** [comment]
@marco-c I meant we should do changes only on _recent_ bugs.

**Comment by marco-c** [comment]
We are going to do this as part of the migration to the new 'Is Regression' field (https://bugzilla.mozilla.org/show_bug.cgi?id=1534280).

**Pull request closed without merging**
