### PR TITLE
Update the protocol from git to https in Readme file

### PR DESCRIPTION
**Pull request by sosa-e**
This PR updates the protocol from git to https in the Installation section located in the Readme file
Discussed in #1853 
## Checklist

- [ ] Type annotations added to new functions
- [ ] Docs added to functions touched in main classes
- [ ] Dry-run produced the expected results
- [ ] The [`to-be-announced`](https://github.com/mozilla/relman-auto-nag/labels/to-be-announced) tag added if this is worth announcing

### CODE REVIEW

**Comment by suhaibmujahid** [comment]
Thank you, @sosa-e! Please drop unrelated changes.

**Comment by suhaibmujahid** [comment]
Please also update the pull request title to something more descriptive.

**Comment by sosa-e** [comment]
My pleasure! I'm not sure why the commit titled "Minimizing config file" was included. Would something like `git push <remote name> <commit hash>:<remote branch name>` only push the `update_readme` branch?

Sure thing! Would something like "Update the protocol from git to https in Readme file" work for the PR title?

**Comment by suhaibmujahid** [comment]
> My pleasure! I'm not sure why the commit titled "Minimizing config file" was included. Would something like `git push <remote name> <commit hash>:<remote branch name>` only push the `update_readme` branch?


No, you can think about commits like a chain. When you push a commit, it will be linked to the previous commits. It seems that when you created this branch, you did not create it based on the master branch; instead, you created it based on the branch you used for the other PR. 

As a simple mitigation, you could revert the unrelated commit:
```
git revert 614159597bfe4fdc3dbaedd08d599573ff29e6de --no-edit
```

> Sure thing! Would something like "Update the protocol from git to https in Readme file" work for the PR title?

Yes, it is better.

**Comment by sosa-e** [comment]
I have reverted the unrelated commit. Should I push the change in the readme file? If I do have to push the change, do I have to create a new PR?

BTW, I greatly appreciate your patience and appreciate you sharing your knowledge. I am learning lots!

**Comment by suhaibmujahid** [comment]
> I have reverted the unrelated commit. Should I push the change in the readme file? If I do have to push the change, do I have to create a new PR?

You do not need to create a new PR. Just push the revert commit to the `update_readme` branch.

**Comment by sosa-e** [comment]
Sweet. I pushed the commit, and, to my knowledge, it appears to only affect README file

**Review by suhaibmujahid — APPROVED** [review]
Thank you, @sosa-e! LGTM.

**Pull request merged**
