### PR TITLE
updated script

### PR DESCRIPTION
**Pull request by Ayushsunny**
updated the not_landed script which was making two separate requests to get user IDs and user nicks.
issue code - #1101

### CODE REVIEW

**Review by marco-c — CHANGES_REQUESTED** [review]
There are a few problems with this PR:
1) You're still making two requests, the idea was to get all information in a single request so that we can avoid the second;
2) In the first request you're getting the nick, but then you're not using it.

**Comment by Ayushsunny** [comment]
> There are a few problems with this PR:
> 
>     1. You're still making two requests, the idea was to get all information in a single request so that we can avoid the second;
> 
>     2. In the first request you're getting the nick, but then you're not using it.
Hello @marco-c 
Sir how to use it ?
I mean here https://github.com/mozilla/relman-auto-nag/blob/c941ae879688387ab9f549d3a487d6b8a6a5c772/auto_nag/scripts/not_landed.py#L266 ?

**Comment by Ayushsunny** [comment]
Sir @marco-c Ping?

**Comment by calixteman** [comment]
@Ayushsunny you get this "nick" value but you don't consume it.

**Comment by marco-c** [comment]
@Ayushsunny part of the work to solve #1101 is figuring out how the script works and how to modify it :)

**Comment by calixteman** [comment]
@Ayushsunny and to be clear we're not your ghost writers: I mean we cannot give you every line of code to write else we'll write the patch ourselves, but we'll be happy to help you.

**Comment by Ayushsunny** [comment]
Hello @marco-c , I have amend the changes.
could you check it now

**Comment by marco-c** [comment]
@Ayushsunny sorry, but the changes aren't really doing what is described in #1101.

**Comment by marco-c** [comment]
For example, you removed `get_nicks` function definition, but you're still using it a few lines later... That's never going to work!

**Comment by Ayushsunny** [comment]
> For example, you removed `get_nicks` function definition, but you're still using it a few lines later... That's never going to work!

Hello @marco-c 
Sir, you mean I have done that deletion process right but we're still calling that function below ?

**Comment by marco-c** [comment]
@Ayushsunny you are removing a function definition, but you are still calling the function that you removed. That's *never* going to work :)
I think it'd be better if you start from some personal project first to learn the basics, then feel free to come back to this!

**Pull request closed without merging**
