### PR TITLE
Use new tools tracking & tracking_untouched instead of the old ones (…

### PR DESCRIPTION
**Pull request by calixteman**
…and prepare the transition to python 3)

### CODE REVIEW

**Comment by calixteman** [comment]
@sylvestre you should accept https://github.com/mozilla/relman-auto-nag/pull/570 in the same time (to avoid to nag dcamp).

**Comment by sylvestre** [comment]
@calixteman can you fix the conflict?

**Comment by calixteman** [comment]
Something is wrong here... need to check.

**Comment by calixteman** [comment]
It's ok to merge it now.

**Pull request merged**
