### PR TITLE
Add an "deprecation" reminder type

### PR DESCRIPTION
**Pull request by badboy**
~~This can be used when none of the other categories are really what you're using it for.~~
This can be used when one should look into removing a deprecated API/feature.

I have a use case for a reminder: Remind me to look into a deprecated functionality in ~3 months.
The existing categories don't really match this.

## Checklist

- [ ] Type annotations added to new functions
- [ ] Docs added to functions touched in main classes
- [ ] Dry-run produced the expected results
- [ ] The [`to-be-announced`](https://github.com/mozilla/relman-auto-nag/labels/to-be-announced) tag added if this is worth announcing

### CODE REVIEW

**Comment by marco-c** [comment]
We decided to have pre-configured categories so we avoid people misusing the system.
Could you tell us a little more about your use case? Do you want to be reminded on a deprecated functionality to remove it after some time? We could add a `reminder-deprecation`.

**Comment by badboy** [comment]
We're tracking Glean in bugzilla. We have some functionality we're rolling out. By Q4 I need to look into the uptake to decide to remove migration code ([bug 1780370](https://bugzilla.mozilla.org/show_bug.cgi?id=1780370)). Normally I would simply create a calendar event to remind me. Because I saw the auto-nag announcement the other day I decided to try that for a change, realizing that the category doesn't exactly fit.
`deprecation` would kind of fit here (not perfectly, but good enough I guess)

**Comment by marco-c** [comment]
I guess the reminder makes sense if, should you leave, another person should get the reminder. If you're the only one that should be reminded, and when you leave the reminder is useless, then the calendar event makes more sense.
I guess this is an example of the first case, right? If you leave, somebody else should get the reminder do remove the migration code.

**Comment by marco-c** [comment]
No I think it's OK, we can add a new `reminder-deprecation`, and your case kind of fits (it's not a deprecation in terms of API, but still...). Unless you can think of a better name for it :)

**Comment by badboy** [comment]
> No I think it's OK, we can add a new `reminder-deprecation`, and your case kind of fits (it's not a deprecation in terms of API, but still...). Unless you can think of a better name for it :)

works for me!

**Review by marco-c — APPROVED** [review]
Thanks!

**Pull request merged**
