### PR TITLE
fix for BUG #2 : BzAPI server on which your software depends is going…

### PR DESCRIPTION
**Pull request by anubnair**
… away

### CODE REVIEW

**Comment by sylvestre** [comment]
The problem that I had was a configuration issue. I removed my comment.

**Comment by anubnair** [comment]
@sylvestre So the fix is working?

**Comment by sylvestre** [comment]
Nope, I wasn't trying with your patch first. I will try tomorrow. Thanks
again
(however, travis is not happy with your change)

**Comment by anubnair** [comment]
@sylvestre I guess the issue was with the configuration. I have updated the fix which you have done and travis is not showing any issue now

**Comment by sylvestre** [comment]
Looks like we are still good.

**Pull request closed without merging**
