### PR TITLE
made automated_release_emails into a stand-alone module by adding

### PR DESCRIPTION
**Pull request by anoopvalluthadam**
'__name__ == __main__' / deleted unnecessory variable / config parsing
in to local

### CODE REVIEW

**Comment by sylvestre** [comment]
What is the point of this change?

**Comment by anoopvalluthadam** [comment]
In case if we need to make this as a module(we might not do) this will
help, isn't it?

And that code looks bad in a plain format :)

On Mon, Nov 2, 2015, 2:39 PM Sylvestre Ledru <notifications@github.com>
wrote:

> What is the point of this change?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/relman-auto-nag/pull/49#issuecomment-152962788>
> .
>
-- 

~anoop_valluthadam

**Comment by sylvestre** [comment]
ok, thanks!

**Comment by anoopvalluthadam** [comment]
Second is, unused variable and old config parsing

**Pull request merged**
