### PR TITLE
Update the rule to unassign good first bugs after 2 months

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@nt1m ok with you?

**Comment by nt1m** [comment]
Sure. I'm only concerned about cases where Phabricator activity has been advancing for 2 months, but not on Bugzilla. That's not too bad, since Phabricator Automation will correct the assignee again anyway. If that starts being too common, then maybe Phabricator activity should be taken in account too.

**Comment by calixteman** [comment]
@sylvestre is it ok to merge ? if yes, please rebase.

**Comment by sylvestre** [comment]
@calixteman yeah, it is ok and let's land it

**Pull request merged**
