### PR TITLE
Use new bugbug pipeline

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by calixteman** [comment]
@marco-c there is an error in CI, could you check ?

**Comment by Lothiraldan** [comment]
@calixteman @marco-c From the error message:
```
  ERROR: Could not find a version that satisfies the requirement rs_parsepatch==0.2.0 (from bugbug==0.0.27->-r requirements.txt (line 18)) (from versions: 0.1.0, 0.1.1)
ERROR: No matching distribution found for rs_parsepatch==0.2.0 (from bugbug==0.0.27->-r requirements.txt (line 18))
```

And checking the distributions files on pypi, `rs_parsepatch` stopped distributing python 2.7 wheels with version 0.1.2. And the build seems to be running Python 2.7.14

**Comment by marco-c** [comment]
scikit-learn 0.21.1 also doesn't have a Python 2 package.
I guess we have to wait until the switch to Python 3 in order to merge this.

**Comment by marco-c** [comment]
Depends on #282.

**Pull request merged**
