### PR TITLE
BUG #2 : BzAPI server on which your software depends is going away

### PR DESCRIPTION
**Pull request by anoopvalluthadam**
@sylvestre  This is the only place we are using old API

### CODE REVIEW

**Comment by sylvestre** [comment]
Looks like we would be still using bzapi here...

**Comment by anoopvalluthadam** [comment]
@sylvestre 

This is the fix, isn't it?

Change:
https://api-dev.bugzilla.mozilla.org/latest/
(or https://api-dev.bugzilla.mozilla.org/1.3/)
to
https://bugzilla.mozilla.org/bzapi/

I hope you might want me to port into new REST API instead of BzAPI, isn't it?

**Comment by sylvestre** [comment]
Sorry about the lag. I just tried and it still fails with:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='bugzilla.mozilla.org', port=443): Max retries exceeded with url: /buglist.cgi?bug_id=1051556,[...]

**Comment by anoopvalluthadam** [comment]
@sylvestre I will take a look in to it. Sorry for the delay.

On Thu, Jan 14, 2016, 3:53 PM Sylvestre Ledru <notifications@github.com>
wrote:

> Sorry about the lag. I just tried and it still fails with:
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='
> bugzilla.mozilla.org', port=443): Max retries exceeded with url:
> /buglist.cgi?bug_id=1051556,[...]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/relman-auto-nag/pull/56#issuecomment-171597568>
> .
>
-- 

~anoop_valluthadam

**Comment by sylvestre** [comment]
Looks like we are still good.

**Pull request closed without merging**
